require("dotenv").config({ path: require("path").join(__dirname, "..", ".env") });

const mongoose = require("mongoose");
const Recipe = require("./models/Recipe");
const Ingredient = require("./models/Ingredient");

const ingredients = [
  { name: "Ayam", category: "protein", sub_category: "Protein Hewani", unit: "gram", common_quantity: 250 },
  { name: "Daging Sapi", category: "protein", sub_category: "Protein Hewani", unit: "gram", common_quantity: 250 },
  { name: "Telur", category: "protein", sub_category: "Protein Hewani", unit: "butir", common_quantity: 6 },
  { name: "Ikan Nila", category: "protein", sub_category: "Protein Hewani", unit: "gram", common_quantity: 300 },
  { name: "Udang", category: "protein", sub_category: "Protein Seafood", unit: "gram", common_quantity: 200 },
  { name: "Cumi", category: "protein", sub_category: "Protein Seafood", unit: "gram", common_quantity: 200 },
  { name: "Ikan Tongkol", category: "protein", sub_category: "Protein Seafood", unit: "gram", common_quantity: 300 },
  { name: "Tahu", category: "protein", sub_category: "Protein Nabati", unit: "gram", common_quantity: 200 },
  { name: "Tempe", category: "protein", sub_category: "Protein Nabati", unit: "gram", common_quantity: 200 },
  { name: "Daging Kambing", category: "protein", sub_category: "Protein Hewani", unit: "gram", common_quantity: 250 },
  { name: "Ikan Salmon", category: "protein", sub_category: "Protein Seafood", unit: "gram", common_quantity: 200 },
  { name: "Kepiting", category: "protein", sub_category: "Protein Seafood", unit: "gram", common_quantity: 300 },
  { name: "Kerang", category: "protein", sub_category: "Protein Seafood", unit: "gram", common_quantity: 200 },
  { name: "Bebek", category: "protein", sub_category: "Protein Hewani", unit: "gram", common_quantity: 300 },
  { name: "Ikan Bandeng", category: "protein", sub_category: "Protein Hewani", unit: "gram", common_quantity: 300 },
  { name: "Nasi Putih", category: "karbo", sub_category: "Nasi", unit: "gram", common_quantity: 200 },
  { name: "Nasi Merah", category: "karbo", sub_category: "Nasi", unit: "gram", common_quantity: 200 },
  { name: "Mie Instan", category: "karbo", sub_category: "Mie", unit: "bungkus", common_quantity: 1 },
  { name: "Mie Telur", category: "karbo", sub_category: "Mie", unit: "gram", common_quantity: 200 },
  { name: "Bihun", category: "karbo", sub_category: "Mie", unit: "gram", common_quantity: 100 },
  { name: "Kentang", category: "karbo", sub_category: "Umbi", unit: "gram", common_quantity: 300 },
  { name: "Ubi", category: "karbo", sub_category: "Umbi", unit: "gram", common_quantity: 250 },
  { name: "Singkong", category: "karbo", sub_category: "Umbi", unit: "gram", common_quantity: 300 },
  { name: "Roti Tawar", category: "karbo", sub_category: "Roti", unit: "lembar", common_quantity: 4 },
  { name: "Pasta", category: "karbo", sub_category: "Mie", unit: "gram", common_quantity: 200 },
  { name: "Bayam", category: "sayur", sub_category: "Sayuran Hijau", unit: "ikat", common_quantity: 1 },
  { name: "Kangkung", category: "sayur", sub_category: "Sayuran Hijau", unit: "ikat", common_quantity: 1 },
  { name: "Sawi", category: "sayur", sub_category: "Sayuran Hijau", unit: "ikat", common_quantity: 1 },
  { name: "Wortel", category: "sayur", sub_category: "Sayuran Umbi", unit: "gram", common_quantity: 200 },
  { name: "Brokoli", category: "sayur", sub_category: "Sayuran Hijau", unit: "gram", common_quantity: 200 },
  { name: "Kol", category: "sayur", sub_category: "Sayuran Hijau", unit: "gram", common_quantity: 300 },
  { name: "Tomat", category: "sayur", sub_category: "Sayuran Buah", unit: "buah", common_quantity: 3 },
  { name: "Terong", category: "sayur", sub_category: "Sayuran Buah", unit: "buah", common_quantity: 2 },
  { name: "Labu Siam", category: "sayur", sub_category: "Sayuran Buah", unit: "buah", common_quantity: 1 },
  { name: "Jagung", category: "sayur", sub_category: "Sayuran Buah", unit: "tongkol", common_quantity: 2 },
  { name: "Bawang Merah", category: "bumbu", sub_category: "Bumbu Dasar", unit: "siung", common_quantity: 5 },
  { name: "Bawang Putih", category: "bumbu", sub_category: "Bumbu Dasar", unit: "siung", common_quantity: 3 },
  { name: "Cabai Merah", category: "bumbu", sub_category: "Cabai", unit: "buah", common_quantity: 5 },
  { name: "Cabai Rawit", category: "bumbu", sub_category: "Cabai", unit: "buah", common_quantity: 5 },
  { name: "Jahe", category: "bumbu", sub_category: "Rempah", unit: "ruas", common_quantity: 2 },
  { name: "Kunyit", category: "bumbu", sub_category: "Rempah", unit: "ruas", common_quantity: 2 },
  { name: "Lengkuas", category: "bumbu", sub_category: "Rempah", unit: "ruas", common_quantity: 2 },
  { name: "Serai", category: "bumbu", sub_category: "Rempah", unit: "batang", common_quantity: 2 },
  { name: "Daun Salam", category: "bumbu", sub_category: "Daun", unit: "lembar", common_quantity: 3 },
  { name: "Daun Jeruk", category: "bumbu", sub_category: "Daun", unit: "lembar", common_quantity: 3 },
  { name: "Kemiri", category: "bumbu", sub_category: "Bumbu Dasar", unit: "butir", common_quantity: 3 },
  { name: "Ketumbar", category: "bumbu", sub_category: "Rempah", unit: "sdt", common_quantity: 1 },
  { name: "Garam", category: "bumbu", sub_category: "Bumbu Dasar", unit: "sdt", common_quantity: 1 },
  { name: "Gula", category: "bumbu", sub_category: "Bumbu Dasar", unit: "sdm", common_quantity: 1 },
  { name: "Kecap Manis", category: "bumbu", sub_category: "Saus", unit: "sdm", common_quantity: 2 },
  { name: "Santan", category: "bumbu", sub_category: "Cairan", unit: "ml", common_quantity: 200 },
];

const recipes = [
  {
    title: "Jagung Sayur Kentang Bowl",
    description: "Cocok untuk Diet, Diabetes, rendah gula. Harga hemat!",
    image_url: "",
    ingredients: [
      { name: "Jagung", quantity: "2", unit: "tongkol" },
      { name: "Kentang", quantity: "200", unit: "gram" },
      { name: "Wortel", quantity: "100", unit: "gram" },
      { name: "Bayam", quantity: "1", unit: "ikat" },
      { name: "Bawang Putih", quantity: "3", unit: "siung" },
      { name: "Garam", quantity: "1", unit: "sdt" },
      { name: "Lada", quantity: "1/2", unit: "sdt" },
    ],
    steps: [
      { order: 1, instruction: "Potong jagung, kentang, dan wortel sesuai selera." },
      { order: 2, instruction: "Rebus kentang dan wortel sampai empuk, tiriskan." },
      { order: 3, instruction: "Tumis bawang putih hingga harum." },
      { order: 4, instruction: "Masukkan jagung, kentang, wortel, dan bayam. Aduk rata." },
      { order: 5, instruction: "Tambahkan garam dan lada. Masak 5 menit." },
      { order: 6, instruction: "Sajikan dalam mangkuk." },
    ],
    category: "Healthy & Clean",
    meal_type: ["lunch", "dinner"],
    tags: ["Healthy & Clean", "Budget Friendly", "Diet", "Diabetes"],
    prep_time: 10,
    cook_time: 20,
    servings: 2,
    nutrition_info: { calories: 250, protein: 8, carbs: 45, fat: 5 },
    suitable_for: ["Diabetes", "Diet"],
    not_suitable_for: [],
  },
  {
    title: "Ayam Goreng Bumbu Kuning",
    description: "Ayam goreng klasik dengan bumbu kuning yang meresap. Cocok untuk makan siang keluarga.",
    image_url: "",
    ingredients: [
      { name: "Ayam", quantity: "500", unit: "gram" },
      { name: "Kunyit", quantity: "3", unit: "ruas" },
      { name: "Bawang Putih", quantity: "5", unit: "siung" },
      { name: "Bawang Merah", quantity: "4", unit: "siung" },
      { name: "Ketumbar", quantity: "1", unit: "sdt" },
      { name: "Garam", quantity: "1", unit: "sdt" },
      { name: "Lengkuas", quantity: "2", unit: "ruas" },
      { name: "Daun Salam", quantity: "2", unit: "lembar" },
    ],
    steps: [
      { order: 1, instruction: "Haluskan kunyit, bawang putih, bawang merah, dan ketumbar." },
      { order: 2, instruction: "Lumuri ayam dengan bumbu halus dan garam. Diamkan 30 menit." },
      { order: 3, instruction: "Rebus ayam dengan lengkuas dan daun salam sampai bumbu meresap." },
      { order: 4, instruction: "Angkat ayam, tiriskan." },
      { order: 5, instruction: "Goreng ayam dalam minyak panas sampai kuning keemasan." },
      { order: 6, instruction: "Sajikan dengan nasi putih dan lalapan." },
    ],
    category: "Traditional",
    meal_type: ["lunch", "dinner"],
    tags: ["Traditional", "Quick & Easy"],
    prep_time: 40,
    cook_time: 30,
    servings: 4,
    nutrition_info: { calories: 350, protein: 30, carbs: 5, fat: 22 },
    suitable_for: [],
    not_suitable_for: ["Kolesterol"],
  },
  {
    title: "Tumis Kangkung Terasi",
    description: "Sayuran sederhana yang lezat dengan bumbu terasi. Murah dan bergizi.",
    image_url: "",
    ingredients: [
      { name: "Kangkung", quantity: "2", unit: "ikat" },
      { name: "Bawang Merah", quantity: "5", unit: "siung" },
      { name: "Bawang Putih", quantity: "3", unit: "siung" },
      { name: "Cabai Merah", quantity: "3", unit: "buah" },
      { name: "Cabai Rawit", quantity: "5", unit: "buah" },
      { name: "Garam", quantity: "1/2", unit: "sdt" },
      { name: "Gula", quantity: "1/2", unit: "sdt" },
      { name: "Kecap Manis", quantity: "1", unit: "sdm" },
    ],
    steps: [
      { order: 1, instruction: "Petik kangkung, cuci bersih, tiriskan." },
      { order: 2, instruction: "Iris bawang merah, bawang putih, dan cabai." },
      { order: 3, instruction: "Panaskan minyak, tumis bawang dan cabai sampai harum." },
      { order: 4, instruction: "Masukkan kangkung, aduk cepat dengan api besar." },
      { order: 5, instruction: "Tambahkan garam, gula, dan kecap manis." },
      { order: 6, instruction: "Aduk rata, masak 2-3 menit. Angkat dan sajikan." },
    ],
    category: "Quick & Easy",
    meal_type: ["lunch", "dinner"],
    tags: ["Quick & Easy", "Budget Friendly", "Traditional"],
    prep_time: 5,
    cook_time: 5,
    servings: 2,
    nutrition_info: { calories: 80, protein: 3, carbs: 10, fat: 4 },
    suitable_for: ["Diet", "Diabetes"],
    not_suitable_for: [],
  },
  {
    title: "Nasi Goreng Spesial",
    description: "Nasi goreng khas Indonesia dengan telur dan sayuran. Cocok untuk sarapan atau makan malam.",
    image_url: "",
    ingredients: [
      { name: "Nasi Putih", quantity: "400", unit: "gram" },
      { name: "Telur", quantity: "2", unit: "butir" },
      { name: "Bawang Merah", quantity: "4", unit: "siung" },
      { name: "Bawang Putih", quantity: "3", unit: "siung" },
      { name: "Cabai Rawit", quantity: "3", unit: "buah" },
      { name: "Kecap Manis", quantity: "2", unit: "sdm" },
      { name: "Garam", quantity: "1/2", unit: "sdt" },
      { name: "Wortel", quantity: "50", unit: "gram" },
      { name: "Kol", quantity: "50", unit: "gram" },
    ],
    steps: [
      { order: 1, instruction: "Iris bawang merah, bawang putih, dan cabai." },
      { order: 2, instruction: "Potong kecil wortel dan kol." },
      { order: 3, instruction: "Panaskan minyak, tumis bumbu iris sampai harum." },
      { order: 4, instruction: "Masukkan telur, orak-arik." },
      { order: 5, instruction: "Tambahkan wortel dan kol, tumis sebentar." },
      { order: 6, instruction: "Masukkan nasi, kecap manis, dan garam. Aduk rata dengan api besar." },
      { order: 7, instruction: "Masak sampai nasi tercampur rata dan sedikit kering." },
      { order: 8, instruction: "Sajikan dengan pelengkap sesuai selera." },
    ],
    category: "Quick & Easy",
    meal_type: ["breakfast", "dinner"],
    tags: ["Quick & Easy", "Traditional", "Budget Friendly"],
    prep_time: 10,
    cook_time: 10,
    servings: 2,
    nutrition_info: { calories: 450, protein: 15, carbs: 65, fat: 15 },
    suitable_for: [],
    not_suitable_for: ["Diabetes"],
  },
  {
    title: "Sop Ayam Bening",
    description: "Sup ayam segar dengan sayuran. Hangat dan menyehatkan, cocok saat cuaca dingin.",
    image_url: "",
    ingredients: [
      { name: "Ayam", quantity: "300", unit: "gram" },
      { name: "Wortel", quantity: "100", unit: "gram" },
      { name: "Kentang", quantity: "150", unit: "gram" },
      { name: "Kol", quantity: "100", unit: "gram" },
      { name: "Bawang Putih", quantity: "3", unit: "siung" },
      { name: "Bawang Merah", quantity: "3", unit: "siung" },
      { name: "Serai", quantity: "1", unit: "batang" },
      { name: "Daun Salam", quantity: "2", unit: "lembar" },
      { name: "Garam", quantity: "1", unit: "sdt" },
    ],
    steps: [
      { order: 1, instruction: "Rebus ayam sampai empuk, angkat dan suwir-suwir." },
      { order: 2, instruction: "Saring kaldu ayam." },
      { order: 3, instruction: "Tumis bawang putih dan bawang merah sampai harum." },
      { order: 4, instruction: "Masukkan tumisan ke dalam kaldu. Tambahkan serai dan daun salam." },
      { order: 5, instruction: "Masukkan wortel dan kentang, masak sampai empuk." },
      { order: 6, instruction: "Tambahkan kol dan ayam suwir. Beri garam." },
      { order: 7, instruction: "Masak 5 menit lagi. Sajikan hangat." },
    ],
    category: "Healthy & Clean",
    meal_type: ["lunch", "dinner"],
    tags: ["Healthy & Clean", "Traditional"],
    prep_time: 15,
    cook_time: 40,
    servings: 4,
    nutrition_info: { calories: 200, protein: 20, carbs: 18, fat: 6 },
    suitable_for: ["Diet"],
    not_suitable_for: [],
  },
  {
    title: "Omelette Sayuran",
    description: "Telur dadar tebal dengan isian sayuran segar. Sarapan sehat dan cepat.",
    image_url: "",
    ingredients: [
      { name: "Telur", quantity: "3", unit: "butir" },
      { name: "Wortel", quantity: "50", unit: "gram" },
      { name: "Brokoli", quantity: "50", unit: "gram" },
      { name: "Tomat", quantity: "1", unit: "buah" },
      { name: "Garam", quantity: "1/4", unit: "sdt" },
      { name: "Lada", quantity: "1/4", unit: "sdt" },
    ],
    steps: [
      { order: 1, instruction: "Potong kecil wortel, brokoli, dan tomat." },
      { order: 2, instruction: "Kocok telur dengan garam dan lada." },
      { order: 3, instruction: "Panaskan sedikit minyak di teflon." },
      { order: 4, instruction: "Tumis sayuran sebentar sampai layu." },
      { order: 5, instruction: "Tuang telur kocok di atas sayuran." },
      { order: 6, instruction: "Masak dengan api kecil sampai bagian bawah matang." },
      { order: 7, instruction: "Lipat omelette, masak sebentar lagi. Sajikan." },
    ],
    category: "Quick & Easy",
    meal_type: ["breakfast"],
    tags: ["Quick & Easy", "Healthy & Clean"],
    prep_time: 5,
    cook_time: 10,
    servings: 1,
    nutrition_info: { calories: 280, protein: 20, carbs: 8, fat: 18 },
    suitable_for: ["Diet"],
    not_suitable_for: ["Kolesterol"],
  },
  {
    title: "Rendang Daging Sapi",
    description: "Masakan khas Padang yang kaya rempah. Cocok untuk acara spesial.",
    image_url: "",
    ingredients: [
      { name: "Daging Sapi", quantity: "500", unit: "gram" },
      { name: "Santan", quantity: "400", unit: "ml" },
      { name: "Bawang Merah", quantity: "8", unit: "siung" },
      { name: "Bawang Putih", quantity: "5", unit: "siung" },
      { name: "Cabai Merah", quantity: "10", unit: "buah" },
      { name: "Jahe", quantity: "3", unit: "ruas" },
      { name: "Lengkuas", quantity: "3", unit: "ruas" },
      { name: "Serai", quantity: "3", unit: "batang" },
      { name: "Daun Jeruk", quantity: "5", unit: "lembar" },
      { name: "Daun Salam", quantity: "3", unit: "lembar" },
      { name: "Kunyit", quantity: "2", unit: "ruas" },
      { name: "Kemiri", quantity: "5", unit: "butir" },
    ],
    steps: [
      { order: 1, instruction: "Potong daging sapi sesuai selera." },
      { order: 2, instruction: "Haluskan bawang merah, bawang putih, cabai, jahe, kunyit, dan kemiri." },
      { order: 3, instruction: "Tumis bumbu halus dengan serai, daun salam, dan daun jeruk sampai harum." },
      { order: 4, instruction: "Masukkan daging, aduk rata dengan bumbu." },
      { order: 5, instruction: "Tuang santan, masak dengan api sedang sambil sesekali diaduk." },
      { order: 6, instruction: "Kecilkan api saat santan mulai menyusut." },
      { order: 7, instruction: "Masak terus sampai santan habis dan daging berwarna coklat kehitaman." },
      { order: 8, instruction: "Rendang siap disajikan." },
    ],
    category: "Traditional",
    meal_type: ["lunch", "dinner"],
    tags: ["Traditional"],
    prep_time: 30,
    cook_time: 180,
    servings: 6,
    nutrition_info: { calories: 450, protein: 35, carbs: 8, fat: 32 },
    suitable_for: [],
    not_suitable_for: ["Kolesterol", "Hipertensi", "Asam Urat"],
  },
  {
    title: "Pepes Tahu Jamur",
    description: "Tahu kukus dengan bumbu rempah dalam bungkus daun pisang. Vegetarian friendly.",
    image_url: "",
    ingredients: [
      { name: "Tahu", quantity: "300", unit: "gram" },
      { name: "Bawang Merah", quantity: "4", unit: "siung" },
      { name: "Bawang Putih", quantity: "2", unit: "siung" },
      { name: "Cabai Rawit", quantity: "3", unit: "buah" },
      { name: "Daun Salam", quantity: "2", unit: "lembar" },
      { name: "Serai", quantity: "1", unit: "batang" },
      { name: "Garam", quantity: "1/2", unit: "sdt" },
      { name: "Daun Jeruk", quantity: "2", unit: "lembar" },
    ],
    steps: [
      { order: 1, instruction: "Hancurkan tahu kasar." },
      { order: 2, instruction: "Iris halus bawang merah, bawang putih, dan cabai." },
      { order: 3, instruction: "Campur tahu dengan bumbu iris, garam, daun salam iris, dan serai iris." },
      { order: 4, instruction: "Bungkus dengan daun pisang, semat dengan lidi." },
      { order: 5, instruction: "Kukus selama 30 menit." },
      { order: 6, instruction: "Bakar sebentar di atas bara untuk aroma asap." },
    ],
    category: "Healthy & Clean",
    meal_type: ["lunch", "dinner"],
    tags: ["Healthy & Clean", "Vegetarian", "Budget Friendly", "Traditional"],
    prep_time: 15,
    cook_time: 35,
    servings: 3,
    nutrition_info: { calories: 120, protein: 10, carbs: 5, fat: 7 },
    suitable_for: ["Diet", "Diabetes", "Kolesterol"],
    not_suitable_for: ["Kedelai"],
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Connected to MongoDB");

    await Ingredient.deleteMany({});
    console.log("Cleared existing ingredients");

    await Recipe.deleteMany({});
    console.log("Cleared existing recipes");

    const createdIngredients = await Ingredient.insertMany(ingredients);
    console.log(`Seeded ${createdIngredients.length} ingredients`);

    const createdRecipes = await Recipe.insertMany(recipes);
    console.log(`Seeded ${createdRecipes.length} recipes`);

    console.log("Seed completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Seed failed:", error.message);
    process.exit(1);
  }
};

seed();
